const strings = {
    buy_now: 'Купить сейчас',
    price: 'Цена',
    item_successfully_added_to_cart: 'Товар успешно добавлен в корзину',
    item_successfully_added_to_favorite: 'Товар успешно добавлен в любимые',
    item_successfully_deleted_to_favorite: 'Товар успешно удален из любимых',
    add_to_cart: 'Добавить в корзину',
    delete_from_cart: 'Удалить из корзины',
    nothing_found: 'Ничего не найдено',
    unknown_error: 'Неизвестная ошибка',
    no_internet_connection: 'Интернет соединение отсутствует',
    are_yoy_sure_logout: 'Вы уверены что хотите выйти из аккаунта?',
    cancel: 'Отмена',
    yes_logout: 'Да выйти',
    you_are_not_authorized: 'Вы не авторизованы',
    open_bot: 'Открыть бота',
    you_are_success_authorized: 'Вы успешно авторизовались',
    place_order: 'Оформить заказ',
    login: 'Войти',
    ups: 'Упс! Что то пошло не так...',
    notifications_is_empty: 'Уведомления отсутствуют',
    notifications: 'Уведомления',
    favorite: 'Избранные',
    cart: 'Корзина',
    go_to_cart: 'Перейти в корзину',
    return_to_home_page: 'Вернуться на главную страницу',
    paste_token: 'Вставить токен',
    paste_token_from_clipboard: 'Вставить токен из буфера обмена',
    invalid_token_format: 'Неверный формат токена',
    token_pasted_successfully: 'Токен успешно вставлен',
};

export default strings;
